name: agentkit_orchestrator_agent
agent:
  type: adk
  model:
    name: gemini-2.0-flash
description: Un agente simple de tipo "Hello World" para demostrar la estructura básica de agentes en el proyecto.
url: http://agentkit-orchestrator-agent:8080
version: 1.0.0
defaultInputModes:
  - text
  - text/plain
defaultOutputModes:
  - text
  - text/plain
capabilities:
  streaming: true

instruction: |
    """
    Eres un agente simple de tipo "Hello World" diseñado para demostrar la estructura básica de agentes en este proyecto.
    
    Tu función principal es saludar al usuario y proporcionar información básica sobre cómo funcionan los agentes en este ecosistema.
    
    Cuando un usuario te envíe un mensaje, debes:
    
    1. **Saludar cordialmente** al usuario.
    2. **Presentarte** como un agente de demostración.
    3. **Explicar brevemente** tu propósito (demostrar la estructura básica de un agente).
    4. **Proporcionar información** sobre la estructura del proyecto y cómo crear nuevos agentes.
    Mantén un tono amigable y didáctico, ya que tu propósito es ayudar a los usuarios a entender cómo funcionan los agentes en este sistema.
    """

skills:
  - id: greet_user
    name: Saludar al Usuario
    description: Saluda al usuario y se presenta como un agente de demostración
    tags:
      - saludo
      - presentación
      - introducción
    examples:
      - "Hola, ¿cómo estás?"
      - "¿Qué es un agente?"
      - "Preséntate"

  - id: explain_project
    name: Explicar Estructura del Proyecto
    description: Explica la estructura básica del proyecto y cómo funcionan los agentes
    tags:
      - estructura
      - proyecto
      - explicación
      - tutorial
    examples:
      - "¿Cómo funciona este proyecto?"
      - "Explícame la estructura de los agentes"
      - "¿Cómo puedo crear mi propio agente?"

tools:
  - type: function
    name: save_session_user
    description: Save user session in Redis
    module_path: session_tools
    function_name: save_session_user
  - type: function
    name: load_session_user
    description: Get historic user session from Redis
    module_path: session_tools
    function_name: load_session_user
  

monitoring:
  phoenix:
    host: phoenix
    port: 6006
    project_name: ORCHESTRATOR